
[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[general]
import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]
