add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$rust\
$golang\
$java\
$kotlin\
$python\
$cmd_duration\
$fill\
$conda\
$gcloud\
$line_break$character"""

palette = "catppuccin_latte"

[username]
style_user = "fg:lavender"
style_root = "fg:maroon"
format = "[$user]($style)"
show_always = false
disabled = false

[hostname]
ssh_only = true
format = "[@$hostname  ](lavender)"
disabled = false

[directory]
style = "fg:mauve"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "fg:pink"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "fg:pink"
format = '[$all_status$ahead_behind ]($style)'

[rust]
symbol = ""
style = "fg:sapphire"
format = '[ $symbol $version]($style)'

[golang]
symbol = ""
style = "fg:sapphire"
format = '[ $symbol $version]($style)'

[java]
symbol = " "
style = "fg:sapphire"
format = '[ $symbol $version]($style)'

[kotlin]
symbol = ""
style = "fg:sapphire"
format = '[ $symbol $version]($style)'

[cmd_duration]
disabled = true
style = "fg:text"
format = "[  $duration]($style)"

[conda]
style = "fg:green"
format = "[$symbol $environment ]($style) "
ignore_base = false

[gcloud]
style = "fg:flamingo"
format = "[$symbol$account(@$domain)($region) ]($style)"

[fill]
symbol = " "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_one_symbol = '[❮](mauve)'
vimcmd_replace_symbol = '[❮](mauve)'
vimcmd_visual_symbol = '[❮](yellow)'

[palettes.catppuccin_mocha]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#24273a"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
