add_newline = true

format = """
[](color_dir)\
$directory\
[](bg:color_git fg:color_dir)\
$git_branch\
$git_status\
[](bg:color_lang fg:color_git)\
$rust\
$golang\
$java\
$kotlin\
$python\
[](bg:surface2 fg:color_lang)\
$cmd_duration\
[ ](fg:surface2)\
$fill\
[](color_cloud)\
$gcloud\
[ ](color_cloud)\
$line_break$character"""

palette = "catppuccin_mocha"

[directory]
style = "fg:text2 bg:color_dir"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:color_git"
format = '[[ $symbol $branch ](fg:text2 bg:color_git)]($style)'

[git_status]
style = "bg:color_git"
format = '[[($all_status$ahead_behind )](fg:text2 bg:color_git)]($style)'

[rust]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:text2 bg:color_lang)]($style)'

[golang]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:text2 bg:color_lang)]($style)'

[java]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:text2 bg:color_lang)]($style)'

[kotlin]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:text2 bg:color_lang)]($style)'

[cmd_duration]
disabled = false
style = "bg:surface2"
format = "[[   $duration ](fg:text2 bg:surface2)]($style)"

[gcloud]
style = "bg:color_cloud"
format = "[[ $symbol$account(@$domain)($region) ](fg:text2 bg:color_cloud)]($style)"

[fill]
symbol = " "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_one_symbol = '[❮](mauve)'
vimcmd_replace_symbol = '[❮](mauve)'
vimcmd_visual_symbol = '[❮](yellow)'

[palettes.catppuccin_mocha]
color_dir = "#c6a0f6"  # mauve
color_git = "#b7bdf8"   # lavender
color_lang = "#f5bde6"  # pink
color_cloud = "#f5a97f"  # peach
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
text2 = "#ffffff"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#24273a"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
